services:
  - type: web
    name: alien-terminal
    env: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py --host 0.0.0.0 --port $PORT